### ISSUE TITLE
Gradle编译错误 紧急！！！

### ISSUE THREAD

**Issue by RayhoWong** [Blankj/RxBus#18]
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find bus.jar (com.blankj:bus:1.0).
  Searched in the following locations:
      https://jcenter.bintray.com/com/blankj/bus/1.0/bus-1.0.jar

之前用1.0版本一直没事，到了今天下午一直编译失败，现在项目卡在这里，什么也做不了！
重新依赖1.5，删除1.0版本依赖，还是出现这个问题！大神你看能不能解决下，跪谢了！

**Comment by Blankj** [comment]
你这个是 utilcode 版本不对，更新到最新就行
