### ISSUE TITLE
粘性事件，无法清除

### ISSUE THREAD

**Issue by zouxianbincc** [Blankj/RxBus#20]
只要注册和发送一个粘性事件，不管是退出界面
还是退出应该，都无法清除这个事件。
这样就会造成只要一打开这个界面，都会找到这个粘性事件发出的通知，
  public void unregister(final Object subscriber) {
        CacheUtils.getInstance().removeDisposables(subscriber);
    }
只是清除了注册的Disposable
但是，粘性事件的
 Map<Class, List<TagMessage>> stickyEventsMap = new ConcurrentHashMap<>();
并没有清除，因为，Map 的key是Callback

所以建议，提供一个方法，指定回收粘性事件或全部回收粘性事件

**Comment by ChenJia-X** [comment]
碰到同样的问题。
建议消费过一次粘性事件后就清除粘性事件

**Comment by onion2333** [comment]
我下载了源码，集成在app里的
在CacheUtils文件里加上
    void removeStickyEvent(final Class eventType, final String tag) {
        synchronized (stickyEventsMap) {
            List<TagMessage> stickyEvents = stickyEventsMap.get(eventType);
            if (stickyEvents != null) {
                stickyEventsMap.remove(eventType);
            }
        }
    }
这段代码
然后在RxBus文件里搜索这段代码callback.onEvent(t);
在这段代码后面加上
 if (isSticky)
    CacheUtils.getInstance().removeStickyEvent(typeClass, tag);

这是我的解决方案

**Comment by onion2333** [comment]
可以在收到消息以后自动清除粘性事件

**Comment by Blankj** [comment]
因为以前是只消费一次，相关 issue 地址：https://github.com/Blankj/RxBus/issues/2

最新版本 1.6 新增 removeSticky 来移除即可。
