### ISSUE TITLE
可以传值吗

### ISSUE THREAD

**Issue by isMeiying** [Blankj/RxBus#21]
发送事件过程中可否将参数传递过去

**Comment by Blankj** [comment]
肯定可以的哈

**Comment by isMeiying** [comment]
@Blankj 感谢回答，那么subscribe只能在activity中吗，在view中是否也可以订阅？

**Comment by Blankj** [comment]
任何 class 都 ok 的，只要 register 了

**Comment by isMeiying** [comment]
@Blankj 非常感谢
