### ISSUE TITLE
Sticky Event

### ISSUE THREAD

**Issue by xiangxm** [Blankj/RxBus#23]
请问博主，我在1.5的版本发送StickyEvent后，可以个地方被消费，但是1.6里面只要有一个地方消费了，这个event在其他地方就不会被消费了，代码不执行。 请问1.6里面有啥办法可以多次消费呢，然后在最后都不需要的时候我再去removeSticky 。

**Comment by Blankj** [comment]
不存在你说的这个问题吧，我 1.5 升级到 1.6 只是新增了 removeSticky 而已。
