### ISSUE TITLE
post一个List类型的数据无法正常接收到

### ISSUE THREAD

**Issue by GaoShin** [Blankj/RxBus#27]
发送事件处：
List<Object> objList = new ArrayList<>();
objList.add(new Object())
//......
RxBus.getDefault().post(wrapper);

接收事件处：
RxBus.getDefault().subscribe(this, AndroidSchedulers.mainThread(), new RxBus.Callback<List<Object>>() {
            @Override
            public void onEvent(List<Object> objList) {
                Log.d("sss", String.format("Objects共%d个", objList.size()));
            }
        });
这个log不打印，换用Rxjava的PublishSubject可以正常接收

**Comment by Blankj** [comment]
对象类型要一一对应，而不是用父类型，比如你这个，就需要用 ArrayList 才行

**Comment by Blankj** [comment]
如果不是一一对应的话，你注册一个 Object 类型，那不是所有的都可以接收了么，这样不合理。

**Comment by GaoShin** [comment]
好的，谢谢
