### ISSUE TITLE
subscribe 时出现 ClassCastException

### ISSUE THREAD

**Issue by IrohFt** [Blankj/RxBus#4]
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
    at .utils.rxbus.RxUtils.getClassFromCallback(RxUtils.java:49)
    at .utils.rxbus.RxBus.subscribe(RxBus.java:129)
    at .rxbus.RxBus.subscribe(RxBus.java:73)
    at .MenuDialog.init(MenuDialog.java:122)

**Comment by IrohFt** [comment]
定位在这里
Type type = ((ParameterizedType) mySuperClass).getActualTypeArguments()[0];

**Comment by IrohFt** [comment]
找到问题了...因为用了lambda表达式...可是为什么...

**Comment by Blankj** [comment]
你先告诉我你怎么调用的，我才能知道发生了啥哈

**Comment by IrohFt** [comment]
RxBus.getDefault().subscribe(this, new RxBus.Callback<String>() {
            @Override
            public void onEvent(String s) {
                if ("replace".equals(s)) {
                    replace();
                }
            }
        });
这样使用正常
 RxBus.getDefault().subscribe(this, (RxBus.Callback<String>) s -> {
            if ("replace".equals(s)) {
                replace();
            }
        });
这样就崩溃...

**Comment by Blankj** [comment]
javac 看下 lambda 生成的代码可以知晓其原因

**Comment by IrohFt** [comment]
好的，谢谢

**Comment by imliujun** [comment]
能兼容lambda吗？
