### ISSUE TITLE
dialogFragment 里面的fragment 发起事件，DialogFragment注册事件，出现这个类型转换问题

### ISSUE THREAD

**Issue by lihuanming** [Blankj/RxBus#5]
java.lang.ClassCastException

java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType

**Comment by MuseYkh** [comment]
我直接在Dialog里注册也碰到了，估计类型上不支持

**Comment by Blankj** [comment]
你 Callback 传入的范型是什么？ 是接口的话 1.2 版本之前会崩溃， 1.2 版本支持接口了已经
