### ISSUE TITLE
CacheUtils存在内存泄漏，即使是我没有使用RxBus的页面

### ISSUE THREAD

**Issue by qianshengta** [Blankj/RxBus#9]
存在泄漏的界面有 
MineFragment,
HomeFragment,
OrderFragment,
AppointmentOrderFragment,
VisitOrderFragment,
InformationFragment。
他们的结构是主体是MainFragment。其他如HomeFragment,OrderFragment,InformationFragment，MineFragment是MainFragment中的子模块。VisitOrderFragment和AppointmentOrderFragment是另外添加到Activity上覆盖MainFragment的页面。
我在MainFragment发出带标签的粘性事件，在HomeFragment中接收，其他页面都没有相关RxBus操作
代码如下：

发送：
    RxBus.getDefault().postSticky(this, "MainFragment");//发送的MainFragment本身实现的接口
    @Override
    public void onDestroyView() {
        super.onDestroyView();
        unbinder.unbind();
        // 注销
        RxBus.getDefault().unregister(this);
    }

接收：
     RxBus.getDefault().subscribeSticky(this, "MainFragment", new RxBus
                .Callback<OnFragmentInteractionListener>() {
            @Override
            public void onEvent(OnFragmentInteractionListener listener) {
                HomeFragment.this.listener = listener;
            }
        });
    @Override
    public void onDestroyView() {
        super.onDestroyView();
        unbinder.unbind();
        // 注销
        RxBus.getDefault().unregister(this);
    }

![screenshot_2018-09-13-11-05-22](https://user-images.githubusercontent.com/29747624/45465115-5c5d1d00-b746-11e8-991d-ddf74c21e75f.png)
![screenshot_2018-09-13-11-05-28](https://user-images.githubusercontent.com/29747624/45465116-5c5d1d00-b746-11e8-80d2-2e9fb19bc7c3.png)
![screenshot_2018-09-13-11-05-34](https://user-images.githubusercontent.com/29747624/45465117-5cf5b380-b746-11e8-8c38-63ef309c6605.png)
![screenshot_2018-09-13-11-05-38](https://user-images.githubusercontent.com/29747624/45465118-5cf5b380-b746-11e8-8b7f-4429af960a60.png)
![screenshot_2018-09-13-11-05-47](https://user-images.githubusercontent.com/29747624/45465119-5cf5b380-b746-11e8-8f6c-b4d12e968704.png)
![screenshot_2018-09-13-11-06-05](https://user-images.githubusercontent.com/29747624/45465120-5d8e4a00-b746-11e8-855d-ed33991dfdd0.png)
![screenshot_2018-09-13-11-06-17](https://user-images.githubusercontent.com/29747624/45465122-5d8e4a00-b746-11e8-99d9-916ac34dd317.png)

**Comment by Blankj** [comment]
你 post 的 event 居然发送 Fragment/Activity ，这不泄露就鬼了，你去试试 EventBus 你这样操作看会泄露不，post 可以是一个普通的实体对象或者接口，不要整 Fragment/Activity。

**Comment by qianshengta** [comment]
我明白你的意思了。意思是说我在Fragment实现了这个接口，然后发送this，我的本意是发送这个接口，其实我是把整个Fragment发送过去了。我应该把这个接口单独实现，然后发送过去对吧

**Comment by Blankj** [comment]
是的，你需要啥就发送啥，不要把涉及到生命周期的东西发过去
